### ISSUE TITLE
@ missing in AccessDenied page

### ISSUE THREAD

**Issue by pranavkm** [aspnet/templating#183]
Original issue: https://github.com/aspnet/Identity/issues/1511

> dotnet new mvc --auth Individual -o Test
> Views/Account/AccessDenied.cshtml 

    @{
     ViewData["Title"] = "Access denied";
    }
    <header>
    <h2 class="text-danger">ViewData["Title"]</h2>
    <p class="text-danger">You do not have access to this resource.</p>
    </header>

    Should have been
    <h2 class="text-danger">@ViewData["Title"]</h2>

**Comment by pranavkm** [comment]
@jbagga could you take this one for the dev branch?

**Comment by jbagga** [comment]
https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Views/Account/AccessDenied.cshtml#L6
It doesn't seem like an issue in dev

**Comment by scottaddie** [comment]
This should've been fixed in https://github.com/aspnet/templating/pull/40.

**Comment by jbagga** [comment]
@scottaddie It was still missing from one of the Views in Identity Area. It's merged in now as part of #184
